### ISSUE TITLE
pkg_publisher: sslkey/sslcert marked as changed every time

### ISSUE THREAD

**Issue by halfninja** [oracle/puppet-solaris_providers#26]
When passing sslkey and sslcert to pkg_publisher, on subsequent runs it thinks the values have changed as the provider always reads them back out as `nil`.

    Notice: /Stage[main]/Oracle::Packages/Pkg_publisher[exa-family]/sslkey: 
      sslkey changed '' to '/var/tmp/pkg.oracle.com.key'
    Notice: /Stage[main]/Oracle::Packages/Pkg_publisher[exa-family]/sslcert: 
      sslcert changed '' to '/var/tmp/pkg.oracle.com.crt'

**Comment by shawnferry** [comment]
The initial provider was written without support for checking the ssl key and cert. We should be able to manage it in a sensible way.

**Comment by shawnferry** [comment]
If you want to try https://github.com/oracle/puppet-solaris_providers/tree/sferry/pkg_publisher it looks like it's working for me

**Comment by shawnferry** [comment]
This has been included in #30
