### ISSUE TITLE
provider 'dns' requires a populated 'options' parameter or it fails

### ISSUE THREAD

**Issue by wfsaxton** [oracle/puppet-solaris_providers#32]
When using the 'dns' provider, if 'options' is not populated, the first Puppet run runs successfully, but subsequent runs gives the following error:

```
Error: Failed to apply catalog: undefined method `gsub' for nil:NilClass
```

I believe this is because of the following code snippet:

https://github.com/oracle/puppet-solaris_providers/blob/f218daab057e0e5b1f837df4aecd7677697d514f/lib/puppet/provider/dns/solaris.rb#L34-L42

That portion relies on the 1st and 3rd columns to be populated in the following svcprop output:

```
# svcprop -p config svc:/network/dns/client
config/domain astring us.oracle.com
config/nameserver net_address 10.209.76.197 10.209.76.198 192.135.82.132
config/options astring
config/search astring us.oracle.com oraclecorp.com oracle.com sun.com
config/value_authorization astring solaris.smf.value.name-service.dns.client
```

The "config/options" line does not have a column 3, so the "value" variables ends up empty and "value.gsub" throws the "nil:NilClass" error.

**Comment by shawnferry** [comment]
Fixed in #33
